services:
  redis:
    image: redis:8.2.1-alpine
    profiles:
      - backend-local
      - local
  backend-app:
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run uvicorn --host 0.0.0.0 main:app
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - redis
    profiles:
      - backend-local
      - local

  celery-worker:
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery -A celery_worker.app worker --loglevel=info -Q local
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - redis
      - backend-app
    profiles:
      - backend-local
      - local
  flower:
    container_name: flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery -A celery_worker flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    depends_on:
      - backend-app
      - redis
      - celery-worker
    profiles:
      - backend-local
      - local
  mock-server:
    build:
      context: ./backend/servers/mock_server
    profiles:
      - local
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb-dev
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--username',
          'admin',
          '--password',
          'password',
          '--authenticationDatabase',
          'admin',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - frontend
      - local

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=$MONGODB_URI
      - MONGODB_DB=$MONGODB_DB
      - BASE_UPLOAD_DIR=$BASE_UPLOAD_DIR
      - NEXT_PUBLIC_CELERY_BASE_URL=$NEXT_PUBLIC_CELERY_BASE_URL
      - NEXT_PUBLIC_CELERY_BASE_URL_SERVER=$NEXT_PUBLIC_CELERY_BASE_URL_SERVER
      - PLAYWRIGHT_BASE_URL=http://localhost:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./.env:/.env:rw
      - ./docker-compose.yml:/docker-compose.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - frontend
      - local

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
