services:
  redis:
    image: redis:8.2.1-alpine
    ports:
      - 6379:6379
    profiles:
      - backend-local
      - local
      - frontend-prod
  backend-app:
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run uvicorn --host 0.0.0.0 main:app
    restart: always
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/.env
      - ./docker-compose.yml:/docker-compose.yml:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
      - ./backend/main.py:/backend/main.py
    depends_on:
      - redis
    profiles:
      - backend-local
      - local
      - frontend-prod

  celery-worker:
    container_name: celery_worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery -A celery_worker.app worker --loglevel=info -Q local
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - redis
      - backend-app
    profiles:
      - backend-local
      - local
      - frontend-prod
  flower:
    container_name: flower
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run celery -A celery_worker flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    depends_on:
      - backend-app
      - redis
      - celery-worker
    profiles:
      - backend-local
      - local
      - frontend-prod
  mock-server:
    build:
      context: ./backend/servers/mock_server
    profiles:
      - local
      - frontend-prod
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb-dev
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--username',
          'admin',
          '--password',
          'password',
          '--authenticationDatabase',
          'admin',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - frontend
      - local
      - frontend-prod

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_CELERY_BASE_URL=$NEXT_PUBLIC_CELERY_BASE_URL
        - NEXT_PUBLIC_RUNPOD_ENDPOINT=$RUNPOD_ENDPOINT
        - NEXT_PUBLIC_CELERY_BASE_URL_SERVER=$NEXT_PUBLIC_CELERY_BASE_URL_SERVER
    container_name: frontend-app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - MONGODB_URI=$MONGODB_URI
      - NEXT_PUBLIC_CELERY_BASE_URL=$NEXT_PUBLIC_CELERY_BASE_URL
      - NEXT_PUBLIC_RUNPOD_ENDPOINT=$RUNPOD_ENDPOINT
      - NEXT_PUBLIC_CELERY_BASE_URL_SERVER=$NEXT_PUBLIC_CELERY_BASE_URL_SERVER
    volumes:
      - uploaded-files:/data/uploads
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - frontend-prod

  frontend-app-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-app-dev
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=$MONGODB_URI
      - NEXT_PUBLIC_CELERY_BASE_URL=$NEXT_PUBLIC_CELERY_BASE_URL
      - NEXT_PUBLIC_RUNPOD_ENDPOINT=$RUNPOD_ENDPOINT
      - NEXT_PUBLIC_CELERY_BASE_URL_SERVER=$NEXT_PUBLIC_CELERY_BASE_URL_SERVER
    volumes:
      - uploaded-files:/data/uploads
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - frontend
      - local

volumes:
  mongodb_data:
  uploaded-files:
networks:
  app-network:
    driver: bridge
