services:
  redis:
    image: redis:8.2.1-alpine
    ports:
      - "6379:6379"
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: uv run uvicorn --host 0.0.0.0 main:app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - redis

  celery-worker:
    container_name: celery_worker
    build: .
    command: uv run celery -A celery_worker worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - redis
      - app
  flower:
    container_name: flower
    build: .
    command: uv run celery -A celery_worker flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    depends_on:
      - app
      - redis
      - celery-worker
  infinite-talk-server:
    build: ./servers/infinite_talk
    ports:
      - "8001:8001"

  zonos-server:
    image: elliotcarery/zonos-server:$ZONOS_SERVER_TAG
    build: ./servers/zonos
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8002:8002"
# Add more fastapi-taskN services as needed
