FROM python:3.12

WORKDIR /app

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

RUN apt-get update && \
    # necessary for legolas to run
    apt-get install -y poppler-utils \
    python3-pip

RUN pip install uv

COPY . /app/

RUN uv sync

ENV PYTHONBUFFERED=1

CMD ["uv", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8001", "main:app"]


