FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

WORKDIR /app

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

RUN apt-get update && \
    apt-get install -y poppler-utils \
    python3-pip \
    espeak-ng \
    git && rm -rf /var/lib/apt/lists/*

RUN pip install uv
RUN git clone https://github.com/Zyphra/Zonos.git /tmp/zonos && \
    mv /tmp/zonos/zonos /app/zonos && \
    rm -rf /tmp/zonos

COPY . /app/

RUN uv sync

ENV PYTHONBUFFERED=1

CMD ["uv", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8002", "main:app"]


